/* DO NOT EDIT THIS FILE - it is machine generated */
#include "renderers/JniRenderer.h"
#include "com_mayohn_vulkan_jni_JniRenderer.h"
#include <bits/strcasecmp.h>
#include <android/native_window.h>
#include <android/native_window_jni.h>

/* Header for class com_mayohn_vulkan_jni_JniRenderer */

/*
 * Class:     com_mayohn_vulkan_jni_JniRenderer
 * Method:    setGLSLPath
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
Renderder *renderer;
char *mGLSLPath;
extern "C" JNIEXPORT void JNICALL Java_com_mayohn_vulkan_jni_JniRenderer_setGLSLPath
        (JNIEnv *env, jobject obj, jstring jpath, jstring tag) {
    mGLSLPath = const_cast<char *>(env->GetStringUTFChars(jpath, 0));
    const char *cTag = env->GetStringUTFChars(tag, 0);
    if (strcasecmp(cTag, "Program01Renderer") == 0) {
        renderer = new Program01Renderer();
    }
}

/*
 * Class:     com_mayohn_vulkan_jni_JniRenderer
 * Method:    onSurfaceCreated
 * Signature: ()V
 */
extern "C" JNIEXPORT void JNICALL Java_com_mayohn_vulkan_jni_JniRenderer_onSurfaceCreated
        (JNIEnv *env, jobject obj, jobject surface) {
    if (NULL != renderer) {
        ANativeWindow* mANativeWindow = ANativeWindow_fromSurface(env, surface);
        renderer->onSurfaceCreated(mANativeWindow);
    }
}

/*
 * Class:     com_mayohn_vulkan_jni_JniRenderer
 * Method:    onSurfaceChanged
 * Signature: (II)V
 */
extern "C" JNIEXPORT void JNICALL Java_com_mayohn_vulkan_jni_JniRenderer_onSurfaceChanged
        (JNIEnv *env, jobject obj, jint width, jint height) {
    if (NULL != renderer) {
        renderer->onSurfaceChanged(width, height);
    }
}

/*
 * Class:     com_mayohn_vulkan_jni_JniRenderer
 * Method:    onDrawFrame
 * Signature: ()V
 */
extern "C" JNIEXPORT void JNICALL Java_com_mayohn_vulkan_jni_JniRenderer_onDrawFrame
        (JNIEnv *env, jobject obj) {
    if (NULL != renderer) {
        renderer->onDrawFrame();
    }
}

/*
 * Class:     com_mayohn_vulkan_jni_JniRenderer
 * Method:    surfaceDestroyed
 * Signature: (II)V
 */
extern "C" JNIEXPORT void JNICALL Java_com_mayohn_vulkan_jni_JniRenderer_surfaceDestroyed
        (JNIEnv *env, jobject obj) {
    if (NULL != renderer) {
        renderer->surfaceDestroyed();
    }
}

